# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.8"

# Define services
services:

 # service-config
 
  service-config:
    build: 
      context: service-config
      dockerfile: Dockerfile     
    ports: 
     - "8888:80" # Map the exposed port 9999 on the container to port 9998 on the host machine
  
     

  # service-register
  service-register :
  
    build: 
      context: service-register
      dockerfile: Dockerfile 
    ports:
      - "5000:8884" # Forward the exposed port 9999 on the container to port 9999 on the host machine
    
     # service-creneaux_requetes
  service-creneaux_requetes :
  
    build: 
      context: service-creneaux_requetes
      dockerfile: Dockerfile 
    ports:
      - "9911:9911" # Forward the exposed port 9999 on the container to port 9999 on the host machine
    
    


 
